[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.1"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/qor/admin"

[[override]]
  name = "github.com/qor/roles"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/qor/qor"

[[constraint]]
  branch = "master"
  name = "github.com/badoux/checkmail"

[[constraint]]
  branch = "master"
  name = "github.com/gin-contrib/sessions"

[[override]]
  branch = "master"
  name = "github.com/boj/redistore"

[[constraint]]
  name = "github.com/google/go-cloud"
  version = "0.3.0"
